{
    charcode:"34n44",
    name:'34th and 44th divisions',
    bias:'3',
    klas:3,
    maker:'gogy',
    fulltags:[],
    tags:['masculine_gender','chinese','group-chacracter','human','warrior','lightskin',],
    attacks:[],
    actions:[],
    passives:[],
    desc:'desc',
    month:1,
    ratings:[],
    cardimglink:[],
    thumbnail-Link:"",
},