{
    charcode:'vegan_gains',
    name:'Aerith Gainsborrough',
    bias:'3',
    klas:1,
    maker:'eno',
    fulltags:[],
    tags:['human','combat-support','game_origins','kindom_hearts_frenchise','feminine_gender','lightskin',],
    attacks:[],
    actions:[],
    passives:[],
    desc:'desc',
    month:8,
    ratings:[[8,7,6],[7,7,8],[7,8,6],[8,7,9],[7,7,7],],
    cardimglink:[],
    thumbnail_link:"",
},
