
var all = ["all"]
var defphas = [5,1,50]
var defphas2 = [7,1,28]
var endrolls = 28//viz: 0-visible 1-tilex 2-submerj

//phase; playerroll?; ? > 1; initial? ; randomized? ; spawn object; 


// var itemdata = [
//     {name:"red bull",spritelink:"",viz:0,desp:1,stats:[],excstat:[]},
//     {name:"blood vial",spritelink:"",viz:0,desp:1,stats:[],excstat:[]},
//     {name:"sprite",spritelink:"",viz:0,desp:1,stats:[],excstat:[]},
//     {name:"solidus",spritelink:"",viz:2,desp:1,stats:[],excstat:[[5,1],[10,1],[15,1]]},
//     {name:"bayonet",spritelink:"",viz:0,desp:1,stats:[],excstat:[]},
//     {name:"Fire Aspect II",spritelink:"",viz:0,desp:1,stats:[],excstat:[]},
//     {name:"1tb cp",spritelink:"",viz:0,desp:1,stats:[],excstat:[]},
//     {name:"grekuball",spritelink:"",viz:0,desp:1,stats:[],excstat:[]},
//     {name:"megalixir",spritelink:"",viz:1,desp:1,stats:[],excstat:[]},
//     {name:"cheese croc",spritelink:"",viz:0,desp:1,stats:[],excstat:[]},
//     {name:"salad",phase:defphas,plerol:0,plent:0,init:1,rand:0,obj:[{name:"Honda Type R Crocs  ",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:["d1-c"]},
//     {name:"uno multcol",phase:[defphas[0],20,50],plerol:0,plent:0,init:1,rand:0,obj:[{name:"Uno Wild Card",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"uno reverse",phase:defphas,plerol:0,plent:1,init:0,rand:0,obj:[{name:"Uno Reverse Card",spritelink:"",viz:0,desp:1,stats:[['ifstat',['spawned',"morethan",2],[['prevnt_spawn','flag']]]],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"uno draw2",phase:defphas,plerol:0,plent:1,init:0,rand:0,obj:[{name:"Uno Draw +2 Card",spritelink:"",viz:0,desp:1,stats:[['ifstat',['spawned',"morethan",2],[['prevnt_spawn','flag']]]],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"uno skip",phase:defphas,plerol:0,plent:1,init:0,rand:0,obj:[{name:"Uno Skip Card",spritelink:"",viz:0,desp:1,stats:[['ifstat',['spawned',"morethan",2],[['prevnt_spawn','flag']]]],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"nichir blade",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:[{name:"nichir blade",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"uno reverse",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:[{name:"Uno Reverse Card",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"uno skip",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:[{name:"Uno Skip Card",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"uno draw2",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:[{name:"Uno Draw +2 Card",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"uno draw4",phase:defphas,plerol:0,plent:0,init:0,rand:1,obj:[{name:"Uno Draw +4 Card",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"fortenitentitite",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"Fortnite card",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"mario mushroom",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"Mario Super Mushroom card",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"mario star",phase:defphas,plerol:0,plent:0,init:0,rand:1,obj:[{name:"Mario Super Star card",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"mario flower",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"Mario Super Fire Flower",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"mario triple shell",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"Mario Triple Green Shell",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"mario red shell",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"Mario Super Red Shell",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"mario blue shell",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"Mario Blue Shell card",spritelink:"",viz:0,desp:1,stats:[['ifstat',['spawned',"morethan",2],[['prevnt_spawn','flag']]]],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"mario bulletbill",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"Mario Bullet Bill",spritelink:"",viz:0,desp:1,stats:[['ifstat',['spawned',"morethan",2],[['prevnt_spawn','flag']]]],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"mario bulletbill",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:[{name:"Mario Bullet Bill",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"mario ligthning",phase:defphas,plerol:0,plent:0,init:1,rand:0,obj:[{name:"Mario Super Lightning",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"mario blooper",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"Mario Super Blooper",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"mario bobomb",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"Mario Super Bob-omb",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"grimace crock",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"Grimace Crocs",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"sardonyx hammer",phase:defphas,plerol:0,plent:0,init:0,rand:1,obj:[{name:"sardonyx hammer",spritelink:"",viz:0,desp:0,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"daisy backpack",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:[{name:"Hiking Backpack",spritelink:"",viz:0,desp:1,stats:[['onpickup',['givetiems','owner',[]]]],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"cement",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"Cement",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"spear inveeter",phase:defphas,plerol:0,plent:0,init:1,rand:1,obj:[{name:"Cement",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},

//     {name:"Soul of Kindness",spritelink:"",viz:0,desp:1,stats:[],excstat:[]},
//     {name:"breverys",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:[{name:"Soul of Bravery",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"patience",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:[{name:"Soul of Patience",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"iusticia",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:[{name:"Soul of Justice",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"persrvir",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:[{name:"Soul of Perseverance",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"integrit",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:[{name:"Soul of Integrity",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"detrmint",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:[{name:"Soul of Determination",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
// ]

// var itemspawn = [
//     {name:"red bull",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"red bull",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"blood vial",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"blood vial",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"sprite",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"sprite",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"solidus",phase:defphas,plerol:0,plent:1,init:0,rand:0,obj:[{name:"solidus",spritelink:"",viz:2,desp:1,stats:[],excstat:[[5,1],[10,1],[15,1]]}],eqs:1,weigth:10,diap:all},
//     {name:"bayonet",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"bayonet",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"Fire Aspect II",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"Fire Aspect II",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"1tb cp",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"1tb cp",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"grekuball",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:[{name:"grekuball",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"megalixir",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"megalixir",spritelink:"",viz:1,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"cheese croc",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"cheese croc",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"salad",phase:defphas,plerol:0,plent:0,init:1,rand:0,obj:[{name:"Honda Type R Crocs  ",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:[12,4]},
//     {name:"uno multcol",phase:[defphas[0],20],plerol:0,plent:0,init:1,rand:0,obj:[{name:"Uno Wild Card",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"uno reverse",phase:defphas,plerol:0,plent:1,init:0,rand:0,obj:[{name:"Uno Reverse Card",spritelink:"",viz:0,desp:1,stats:[['ifstat',['spawned',"morethan",2],[['prevnt_spawn','flag']]]],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"uno draw2",phase:defphas,plerol:0,plent:1,init:0,rand:0,obj:[{name:"Uno Draw +2 Card",spritelink:"",viz:0,desp:1,stats:[['ifstat',['spawned',"morethan",2],[['prevnt_spawn','flag']]]],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"uno skip",phase:defphas,plerol:0,plent:1,init:0,rand:0,obj:[{name:"Uno Skip Card",spritelink:"",viz:0,desp:1,stats:[['ifstat',['spawned',"morethan",2],[['prevnt_spawn','flag']]]],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"nichir blade",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:[{name:"nichir blade",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"uno reverse",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:[{name:"Uno Reverse Card",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"uno skip",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:[{name:"Uno Skip Card",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"uno draw2",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:[{name:"Uno Draw +2 Card",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"uno draw4",phase:defphas,plerol:0,plent:0,init:0,rand:1,obj:[{name:"Uno Draw +4 Card",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"fortenitentitite",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"Fortnite card",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"mario mushroom",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"Mario Super Mushroom card",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"mario star",phase:defphas,plerol:0,plent:0,init:0,rand:1,obj:[{name:"Mario Super Star card",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"mario flower",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"Mario Super Fire Flower",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"mario triple shell",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"Mario Triple Green Shell",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"mario red shell",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"Mario Super Red Shell",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"mario blue shell",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"Mario Blue Shell card",spritelink:"",viz:0,desp:1,stats:[['ifstat',['spawned',"morethan",2],[['prevnt_spawn','flag']]]],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"mario bulletbill",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"Mario Bullet Bill",spritelink:"",viz:0,desp:1,stats:[['ifstat',['spawned',"morethan",2],[['prevnt_spawn','flag']]]],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"mario bulletbill",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:[{name:"Mario Bullet Bill",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"mario ligthning",phase:defphas,plerol:0,plent:0,init:1,rand:0,obj:[{name:"Mario Super Lightning",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"mario blooper",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"Mario Super Blooper",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"mario bobomb",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"Mario Super Bob-omb",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"grimace crock",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"Grimace Crocs",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"sardonyx hammer",phase:defphas,plerol:0,plent:0,init:0,rand:1,obj:[{name:"sardonyx hammer",spritelink:"",viz:0,desp:0,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"daisy backpack",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:[{name:"Hiking Backpack",spritelink:"",viz:0,desp:1,stats:[['onpickup',['givetiems','owner',[]]]],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"cement",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:[{name:"Cement",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"spear inveeter",phase:defphas,plerol:0,plent:0,init:1,rand:1,obj:[{name:"Cement",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},

//     {name:"kindness",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:[{name:"Soul of Kindness",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"breverys",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:[{name:"Soul of Bravery",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"patience",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:[{name:"Soul of Patience",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"iusticia",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:[{name:"Soul of Justice",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"persrvir",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:[{name:"Soul of Perseverance",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"integrit",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:[{name:"Soul of Integrity",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
//     {name:"detrmint",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:[{name:"Soul of Determination",spritelink:"",viz:0,desp:1,stats:[],excstat:[]}],eqs:0,weigth:10,diap:all},
// ]

//itemobject despanable:bool despawnOnRound:???

var itemdata = [
    {name:"grekuball",                spritelink:"grekuball.png",cardlink:"grekuball.png",viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"sardonyx hammer",          spritelink:"sardonyx_hammer.png",cardlink:"sardonyx_hammer_v1.png",viz:0,desp:0,weigth:10,stats:[],excstat:[]},

    {name:"Soul of Kindness",         spritelink:"backback_potato.png",cardlink:"kindness.png",viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Soul of Bravery",          spritelink:"backback_potato.png",cardlink:"breverys.png",viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Soul of Patience",         spritelink:"backback_potato.png",cardlink:"patience.png",viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Soul of Justice",          spritelink:"backback_potato.png",cardlink:"iusticia.png",viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Soul of Perseverance",     spritelink:"backback_potato.png",cardlink:"persrvir.png",viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Soul of Integrity",        spritelink:"backback_potato.png",cardlink:"integrit.png",viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Soul of Determination",    spritelink:"backback_potato.png",cardlink:"detrmint.png",viz:0,desp:1,weigth:10,stats:[],excstat:[]},

    {name:"red bull",                 spritelink:"backback_potato.png",cardlink:"red_bull.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"blood vial",               spritelink:"backback_potato.png",cardlink:"blood_vial.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"sprite",                   spritelink:"backback_potato.png",cardlink:"sprite_bootle.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    // {name:"solidus",                  spritelink:"backback_potato.png",cardlink:"iusticia.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"bayonet",                  spritelink:"backback_potato.png",cardlink:"bayonet.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Fire Aspect II",           spritelink:"backback_potato.png",cardlink:"fire_aspect.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"1tb cp",                   spritelink:"backback_potato.png",cardlink:"terabites.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"megalixir",                spritelink:"backback_potato.png",cardlink:"megalixir.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"cheese croc",              spritelink:"backback_potato.png",cardlink:"cheese_crocks.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Honda Type R Crocs",       spritelink:"backback_potato.png",cardlink:"honda_crocks.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Uno Wild Card",            spritelink:"backback_potato.png",cardlink:"uno_wildcard.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Uno Reverse Card",         spritelink:"backback_potato.png",cardlink:"unoreverse_card.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Uno Draw +2 Card",         spritelink:"backback_potato.png",cardlink:"unodraw2_card.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Uno Skip Card",            spritelink:"backback_potato.png",cardlink:"unoskip_card.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"nichir blade",             spritelink:"backback_potato.png",cardlink:"nichirin_blade.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Uno Reverse Card",         spritelink:"backback_potato.png",cardlink:"unoreverse_card.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Uno Skip Card",            spritelink:"backback_potato.png",cardlink:"unoskip_card.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Uno Draw +2 Card",         spritelink:"backback_potato.png",cardlink:"unodraw2_card.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Uno Draw +4 Card",         spritelink:"backback_potato.png",cardlink:"unoplus4_card.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Fortnite card",            spritelink:"backback_potato.png",cardlink:"fortnite_card.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Mario Super Mushroom card",spritelink:"backback_potato.png",cardlink:"mario_supermshroom.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Mario Super Star card",    spritelink:"backback_potato.png",cardlink:"mario_superstar.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Mario Super Fire Flower",  spritelink:"backback_potato.png",cardlink:"mario_fireflower.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Mario Triple Green Shell", spritelink:"backback_potato.png",cardlink:"mario_3greenshell.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Mario Super Red Shell",    spritelink:"backback_potato.png",cardlink:"mario_redshell.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Mario Blue Shell card",    spritelink:"backback_potato.png",cardlink:"mario_blueshell.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Mario Bullet Bill",        spritelink:"backback_potato.png",cardlink:"mario_bulletbill.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Mario Bullet Bill",        spritelink:"backback_potato.png",cardlink:"mario_bulletbill.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Mario Super Lightning",    spritelink:"backback_potato.png",cardlink:"mario_lighning.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Mario Super Blooper",      spritelink:"backback_potato.png",cardlink:"mario_blooper.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Mario Super Bob-omb",      spritelink:"backback_potato.png",cardlink:"mario_bobomb.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Grimace Crocs",            spritelink:"backback_potato.png",cardlink:"persrvir.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Hiking Backpack",          spritelink:"backback_potato.png",cardlink:"hiking_backpack.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"Cement",                   spritelink:"backback_potato.png",cardlink:"cement.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
    {name:"spear inveeter",           spritelink:"backback_potato.png",cardlink:"iverted_heaven.png"                  ,viz:0,desp:1,weigth:10,stats:[],excstat:[]},
]

var itemspawn = [
    {name:"grekuball",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:['grekuball'],eqs:0,weigth:10,diap:all},

    {name:"sardonyx hammer",phase:defphas,plerol:0,plent:0,init:1,rand:1,obj:["sardonyx hammer"],eqs:0,weigth:10,diap:all},
    
    {name:"kindness",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:["Soul of Kindness",     ],eqs:0,weigth:10,diap:all},
    {name:"breverys",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:["Soul of Bravery",      ],eqs:0,weigth:10,diap:all},
    {name:"patience",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:["Soul of Patience",     ],eqs:0,weigth:10,diap:all},
    {name:"iusticia",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:["Soul of Justice",      ],eqs:0,weigth:10,diap:all},
    {name:"persrvir",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:["Soul of Perseverance", ],eqs:0,weigth:10,diap:all},
    {name:"integrit",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:["Soul of Integrity",    ],eqs:0,weigth:10,diap:all},
    {name:"detrmint",phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:["Soul of Determination",],eqs:0,weigth:10,diap:all},


    
    {name:"red bull",          phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:["red bull",                 ],eqs:0,weigth:10,diap:all},
    {name:"blood vial",        phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:["blood vial",               ],eqs:0,weigth:10,diap:all},
    {name:"sprite",            phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:["sprite",                   ],eqs:0,weigth:10,diap:all},
    // {name:"solidus",           phase:defphas,plerol:0,plent:1,init:0,rand:0,obj:["solidus",                  ],eqs:1,weigth:10,diap:all},
    {name:"bayonet",           phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:["bayonet",                  ],eqs:0,weigth:10,diap:all},
    {name:"Fire Aspect II",    phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:["Fire Aspect II",           ],eqs:0,weigth:10,diap:all},
    {name:"1tb cp",            phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:["1tb cp",                   ],eqs:0,weigth:10,diap:all},
    // {name:"grekuball",         phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:["grekuball",                ],eqs:0,weigth:10,diap:all},
    {name:"megalixir",         phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:["megalixir"                 ],eqs:0,weigth:10,diap:all},
    {name:"cheese croc",       phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:["cheese croc",              ],eqs:0,weigth:10,diap:all},
    {name:"salad",             phase:defphas,plerol:0,plent:0,init:1,rand:0,obj:["Honda Type R Crocs  ",     ],eqs:0,weigth:10,diap:[12,4]},
    {name:"uno multcol",     phase:[5,20,50],plerol:0,plent:0,init:1,rand:0,obj:["Uno Wild Card",            ],eqs:0,weigth:10,diap:all},
    {name:"uno reverse",       phase:defphas,plerol:0,plent:1,init:0,rand:0,obj:["Uno Reverse Card"          ],eqs:0,weigth:10,diap:all},
    {name:"uno draw2",         phase:defphas,plerol:0,plent:1,init:0,rand:0,obj:["Uno Draw +2 Card"          ],eqs:0,weigth:10,diap:all},
    {name:"uno skip",          phase:defphas,plerol:0,plent:1,init:0,rand:0,obj:["Uno Skip Card"             ],eqs:0,weigth:10,diap:all},
    {name:"nichir blade",      phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:["nichir blade",             ],eqs:0,weigth:10,diap:all},
    {name:"uno reverse",       phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:["Uno Reverse Card",         ],eqs:0,weigth:10,diap:all},
    {name:"uno skip",          phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:["Uno Skip Card",            ],eqs:0,weigth:10,diap:all},
    {name:"uno draw2",         phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:["Uno Draw +2 Card",         ],eqs:0,weigth:10,diap:all},
    {name:"uno draw4",         phase:defphas,plerol:0,plent:0,init:0,rand:1,obj:["Uno Draw +4 Card",         ],eqs:0,weigth:10,diap:all},
    {name:"fortenitentitite",  phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:["Fortnite card",            ],eqs:0,weigth:10,diap:all},
    {name:"mario mushroom",    phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:["Mario Super Mushroom card",],eqs:0,weigth:10,diap:all},
    {name:"mario star",        phase:defphas,plerol:0,plent:0,init:0,rand:1,obj:["Mario Super Star card",    ],eqs:0,weigth:10,diap:all},
    {name:"mario flower",      phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:["Mario Super Fire Flower",  ],eqs:0,weigth:10,diap:all},
    {name:"mario triple shell",phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:["Mario Triple Green Shell", ],eqs:0,weigth:10,diap:all},
    {name:"mario red shell",   phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:["Mario Super Red Shell",    ],eqs:0,weigth:10,diap:all},
    {name:"mario blue shell",  phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:["Mario Blue Shell card",    ],eqs:0,weigth:10,diap:all},
    {name:"mario bulletbill",  phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:["Mario Bullet Bill",        ],eqs:0,weigth:10,diap:all},
    {name:"mario bulletbill",  phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:["Mario Bullet Bill",        ],eqs:0,weigth:10,diap:all},
    {name:"mario ligthning",   phase:defphas,plerol:0,plent:0,init:1,rand:0,obj:["Mario Super Lightning",    ],eqs:0,weigth:10,diap:all},
    {name:"mario blooper",     phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:["Mario Super Blooper",      ],eqs:0,weigth:10,diap:all},
    {name:"mario bobomb",      phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:["Mario Super Bob-omb",      ],eqs:0,weigth:10,diap:all},
    {name:"grimace crock",     phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:["Grimace Crocs",            ],eqs:0,weigth:10,diap:all},
    {name:"sardonyx hammer",   phase:defphas,plerol:0,plent:0,init:0,rand:1,obj:["sardonyx hammer"           ],eqs:0,weigth:10,diap:all},
    {name:"daisy backpack",    phase:defphas,plerol:1,plent:0,init:0,rand:0,obj:["Hiking Backpack"           ],eqs:0,weigth:1000,diap:all},
    {name:"cement",            phase:defphas,plerol:0,plent:1,init:0,rand:1,obj:["Cement",                   ],eqs:0,weigth:10,diap:all},
    {name:"spear inveeter",    phase:defphas,plerol:0,plent:0,init:1,rand:1,obj:["spear inveeter"            ],eqs:0,weigth:10,diap:all},
]

