var ratings = [
    ["riku",[10,8,9,"gogy",""]],
    ["riku",[10,8,9,"saba","that megumi strat while hugging the wall is going to be atrocious"]],
    ["destiny_debater",[10,9,10,"gogy","coldest card so far"]],
    ["destiny_debater",[9,9,10,"michael",""]],
    ["elegast_ruina",[8,7,10,"amadeo",""]],
    ["elegast_ruina",[10,8,9,"saba",""]],
    ["elegast_ruina",[10,8,10,"gogy",""]],
    ["tminad_basketball",[8,8,9,"saba",""]],
    ["tminad_basketball",[8,8,9,"gogy",""]],
    ["tminad_basketball",[8,9,7,"eno",""]],
    ["tminad_basketball",[9,6,9,"joshua",""]],
    ["grapple_pilot",[8,8,9,"gogy",""]],
    ["grapple_pilot",[10,6,9,"joshua",""]],
    ["grapple_pilot",[10,7,9,"saba",""]],
    ["grapple_pilot",[9,9,9,"amadeo",""]],
    ["joshua_templar",[8,8,10,"amadeo",""]],
    ["joshua_templar",[10,7,10,"saba","alright sigmas extremely powerful card and i fucking mean it btw that multiply by count is insane"]],
    ["joshua_templar",[8,6,10,"joshua",""]],
    ["joshua_templar",[9,9,10,"gogy",""]],
    ["sinclair_sinner",[10,8,7,"amadeo",""]],
    ["sinclair_sinner",[10,8,7,"saba",""]],
    ["sinclair_sinner",[10,8,8,"eno",""]],
    ["rukia_kuchiki",[10,9,10,"viie","nice design, cool frames, nice icons, good color scheme, perfect readability"]],
    ["rukia_kuchiki",[10,10,10,"gogy",""]],
    ["rukia_kuchiki",[10,10,10,"saba",""]],
    ["rukia_kuchiki",[9,6,10,"gogy",""]],
    ["dagon_deamon",[7,8,10,"eno","i would never think of this shit"]],
    ["dagon_deamon",[8,8,9,"gogy",""]],
    ["super_idol",[10,10,10,"saba",""]],
    ["super_idol",[10,10,10,"eno","bro put all his budget on this card holy shit its so good no glaze but id put it up on my wall as a painting and id call it the mamadeoliza. i love how the abilities match with the fish you just posted and its fairly balanced on its own too. i remember seeing you make this shit the fucking theories and ideas this nigga has for the dumbest shit is insane MEGAAAAA GIGGAAAAAA GRUG"]],
    ["super_idol",[10,6,10,"joshua","Design is fine I don't have to comment on it, apart from maybe more compact text or a smarter way to place the abilities in the card. Balance, is almost downright bad. Creativity love it (love the fact you used my temperature idea, but no bottle of water.)"]],
    ["super_idol",[10,8,10,"gogy",""]],
    ["dunkleosteus_placodermi",[10,10,10,"saba","https://tenor.com/view/kj-final-ride-death-punch-gif-1152880950824854635"]],
    ["dunkleosteus_placodermi",[10,10,10,"joshua","I have an issue with the orange text being annoying to read. I guess it's perfectly fine to fight against, unless you factor in the dmg reduction negation + dmg reduction himself that would counter the balancing. ancient fish also love you added the classification of of the type of fish"]],
    ["dunkleosteus_placodermi",[9,9,10,"eno","good googly moogly this is great but the text on the box below match with its bg making the text look darker but maybe its just the fact that im reading this in the middle of the street. the roll on the first attack being 16 is kinda fucking insane but otherwise very balanced. average amadeo creativity with animals i have never even heard of"]],
    ["homeless_man",[9,9,9,"eno","despite the great overall feeling it barely has enough eye candy and its very basic but for a george card its something hard to achieve so a nine will do. nothing much i can say except i wanna see how he plays out he seems like a great legendary. oh my malevolent gyat you cooked and im gonna glaze this all day like a honeybun"]],
    ["nobara_kugisagi",[10,9,8,"viie","i love the color scheme, bit joshua looking icons, cool and normal attacks that creativityat this point"]],
    ["nobara_kugisagi",[10,9,9,"gogy","hurts my eyes"]],
    ["kaboom_kadir",[10,10,10,"michael",""]],
    ["kaboom_kadir",[10,10,10,"amadeo","magnum opus of cards, this is The Card"]],
    ["kaboom_kadir",[8,9,10,"gogy",""]],
    ["kaboom_kadir",[10,10,10,"saba",""]],
    ["kaboom_kadir",[6,7,7,"joshua",""]],
    ["v1_machine",[7,9,10,"saba",""]],
    ["v1_machine",[7,9,10,"eno",""]],
    ["v1_machine",[8,7,10,"joshua",""]],
    ["anti_goner",[10,9,9,"gogy",""]],
    ["anti_goner",[10,10,10,"joshua",""]],
    ["anti_goner",[10,10,10,"eno",""]],
    ["anti_goner",[7,7,9,"amadeo","card follows a strict collor scheme while having very detailed icons therefore they function very well explaining the moves/helping visualize them id say playng around with the fonts would be interesting other then that the card is perfectly readable and i cant argue againts that.<br>card is a power house max dps no bullshit just straight to the point mean gooner killing machine damage makesup for the lack of pussy passives with a very creative passive that makes the anti gooner acutally have to use brains to use since you dont want to get yourslef staggered this single passive unironically makes most your moves very balanced but you still have to fix a few errors here and there, to use this card to the maximum use it as a last resort something you can deploy do dmg with and get out since he cant take allot of attacks but utilizing him with hsc or terence could be deadly.<br>entirly custom made card all moves are refind and thought of expect the domain which pisses me of grei give him a bankai instead nigger"]],
    ["grimmjow_jaegerjaquez",[10,9,8,"amadeo",""]],
    ["grimmjow_jaegerjaquez",[10,8,9,"saba",""]],
    ["grimmjow_jaegerjaquez",[10,9,10,"eno",""]],
    ["dr_coomer",[7,8,9,"amadeo",""]],
    ["dr_coomer",[9,8,10,"eno",""]],
    ["anby_burger",[10,9,9,"viie","im sorry i cant give a big commentary for this"]],
    ["anby_burger",[9,9,9,"gogy",""]],
    ["anby_burger",[8,9,10,"joshua",""]],
    ["anby_burger",[10,9,9,"saba",""]],
    
    ["gon_freecs",[9,8,10,"saba",""]],
    ["gon_freecs",[9,8,9,"gogy",""]],
    ["gon_freecs",[9,9,10,"polmich",""]],
    ["gon_freecs",[7,8,9,"",""]],

    ["gin_ichimaru",[10,8,10,"saba","im sad you didnt call it Gin Freakymaru Jumpscare"]],
    ["gin_ichimaru",[10,10,10,"amadeo",""]],

    ["mr_lul",[9,9,9,"saba",""]],
    ["mr_lul",[9,8,9,"eno","Bg is INSANELY BRIGHT MY GUY,sometimes the stroke blends in with the bg which makes almost 0 diff <br>(Top tier ragebait) (20figsbtw)"]],
    ["mr_lul",[9,8,10,"joshua",""]],

    ["kms_roon",[10,8,9,"eno",""]],
    ["kms_roon",[10,8,10,"polmich",""]],
    ["kms_roon",[10,6,10,"gogy",""]],
    ["kms_roon",[8,7,10,"michael",'(Very much an improvement on version 1.0 that was made eons ago. However, there are gripes I have with this card. Mainly, the text looking big red and black boxes with hints of orange. However, I am aware that there was not much you could have solved in that department so I did not fault you too much for that, you did what you could have there. Secondly, there is no watermark (I will flip). Third off, the "KMS Roon", "Normal Meelee Attacks" and "Special Meelee Attacks" are too dark. Perhaps changing the shade of red to make it glow more perchance. It sounds like I do not have anything noteworthy to say about the design of this card, which is incorrect. I very much appreciate your time and effort that you have put into the icons here. For that, thank you)(Good, needs lots of nerfs. Such as, cooldowns and about of dmg certain attacks do)']],

    ["mr_donut",[10,10,10,"amadeo",""]],
    ["mr_donut",[10,10,10,"saba",""]],
    
    ["coyote_stark",[10,9,10,"saba",""]],
    ["coyote_stark",[10,9,10,"amadeo",""]],
    ["coyote_stark",[10,9,10,"gogy",""]],
    ["coyote_stark",[10,9,10,"eno",""]],
    
    ["bleeder_quagmire",[6,8,9,"eno","D: im so sorry it would have been a 1 if it weren’t for you changing it so i think its more than enough. With enough work it could have been joated. B: pretty goated not much to say C:oh my GOD im going to bust a fat load over the creativity i love the bleed idea cause i was gonna use the same thing on a character with electrocution a couple months ago "]],
    ["bleeder_quagmire",[8,9,9,"joshua",""]],
    ["bleeder_quagmire",[9,8,10,"gogy",""]],
    
    
    ["bilal_olatunji",[8,8,9,"joshua","Like i said before the card feels bleak,its not that itneresting to look at, the cons are well made and I can tell what you tried to do witht he fade on the overcolouring of them, but again the cards missing fundemental looks, like proper detailed background, or other details that help it stand out. Next, the card type on the bottom is a cool idea, might fit your card style cant see it being incoorporated to something like mine which is probably reaching the end of its evolution. my other issue is the fact that it looks like one of those fucking old amadeo cards, nothing like the renowned tardigrada or the spertozoid fucker pink nigga from steven universe,it looks as if old kai and saxton hale had a child and the child was nigerian. and my last issue is the lack of contrast in the design,literally, because its so bleak theres barely any sort of contrast in the card to make it stand out.\nB8: balanced, cant say much here.\nC9: average amadeo card,usually creative, cant say shit here either,but some moves feel repeated from other cards."]],
    ["bilal_olatunji",[8,8,10,"eno",""]],
    ["bilal_olatunji",[8,8,10,"gogy","D8 I like the that you took inspiration from diorns designs and it also looks nicley made (please add a fucking stroke why cant you learn this)\nB8 overall balanced although the fire trail is pretty situational so im dedecuting points on that.\nC10 bilal ultra sigma W?"]],
    ["bilal_olatunji",[8,8,10,"saba","I really dont like how barebones the card looks in my opinion, it dosent feel nice to look at either, theres no stroke or anything on it\ntheres 2 triangles in the corners to up the design up a bit but thats it\nits like a old era george or amadeo card"]],

    ["bilal_olatunji",[6,8,9,"joshua",""]],
    // ["bilal",[6,10,10,"gogy",""]],
    
    ["peter_griffin",[8,9,10,"eno","could use more work though love that is was inspired by manga type design. your average card not much to say here, really creative especially on the domain and some other abilities but thats all i can say. Werent it for the domain it would have been a 8 or 9"]],
    ["peter_griffin",[8,7,9,"joshua"," D: because the design is pretty empte, i like the overall look to it, manga pannels etc, but again it  feels bland and it has too much space, the icons are great, i aswellappriacte the fact that you started to change up your style a bit in comparisson with your old bullshit. B: because this doesnt seem like the best card to fight against, but neither the worst, overall most of the skills are pretty ballanced with dmg averaging around 60-120, which is normal for legendaries. the domain might be a tad bit broken but i like the ideas C: because i gave you points in the specials and the passives alongwith the domain, the normals seemed pretty bland and repeated on like other characters, although ill say that this couldve been done without a fucking domain expansion you couldve jsut made a normal cutwaya last special move or some shit you didnt have to do a fucking domain expansion, the black flash is oversued, normal barragae blah blah blah, meg being brought out is funny and creative, ipretty sure enea suggested that multiple times and etc. <br><br>overall i loved the card but you can do better in my opinion."]],
    ["peter_griffin",[8,9,10,"amadeo","D: ill start with glazing, icons are nutty, manga thing is smart, white is well mixed, font now  i think too much astate one thing that would fix that is frame it also feels a bit bland so adding spice to it like maybe some more visual candy could work for my brain rot brain, idk about this one but maybe have different backgrounds for each or only the passive/domain B: best thing i can compare him too is garou, the generalist while being mobile posses decent dmg and surprisingly alot of poison, one thing that i would enjoy more is experimenting eith knockback since his unique pilk allows him to pop off into that scenario C: this card is like wine in a sense since older it got the better the moves became (i dont drink wine) but taking ideas from me and eno and blending them into this is quite good but i do feel like you overdid it a bit since some moves feel like they are just tryng to fill a spot other then that domain is a cliP farm like an ipad kid and the passives are aight"]],
    ["peter_griffin",[9,7,10,"saba","D9 i fw the manga deisgn<br>B7- is that fucking Kokushibo and MOSB as a fucking domain expansion enemy?<br>C10 UNIQUE DOMAIN!!!!!!"]],
    // ["peter_griffin",[7,8,4,"gabe",""]],

    ["v_vergil",[10,10,10,"viie","i love this card and its feel looks great, Vs stagger being commutative makes it balanced and creativity needs no comment"]],
    ["v_vergil",[9,7,9,"joshua",""]],
    ["v_vergil",[10,8,8,"amadeo","D10<br>purple isnt my favorite collor but micheal and josh will rape so aight, background is nutty the frame goes hard the icons are fire idk how but i want to give the design a creativity rating id give it c10 in design alr holy yap sesh lets finnish this, fonts are non existent the text size is perfect  and the name behind him is cold basically eno meta popping off<br><br>B8 like most summoner shikigami classes they are always annoying to fight ive said this for megumi and ill say it again but one thing you did do is gave him less ho and no dmg reduction which will put you into my top 10 sigma moments all animals have their use but for my playstyle id personally use the arbiter<br><br>C8 i mean like, its nothing out of the world but i do love the way you pulled of the stagger breeding so aight igen."]],
    ["v_vergil",[10,7,9,"saba","[ BLACKSOULS GRIND NEVER STOPS ]"]],

    ["jetstream_sam",[10,9,9,"gogy","D9 I like the design on it add the stroke on text icons are really good<br><br>B9 pretty alright might cause problems<br><br>C9 nothing much to say here"]],
    ["jetstream_sam",[10,8,9,"joshua",""]],
    ["jetstream_sam",[10,10,8,"amadeo","D10 cant say much hear love the collor combination the icons are fresh a specially the 10th one background and fonts are good<br><br>B10 fun to play against the stg drain helps severely since it just feels like a fair fight against block and dodge dies are sparse, love the mobility based dps<br><br>C8ofc few moves you invented on your own but there is nothing really revolutionary going on here so C8 feels right"]],

    ["saxton_hale",[8,9,8,"eno",""]],
    ["saxton_hale",[9,9,7,"gogy",""]],
    ["saxton_hale",[10,9,9,"joshua",""]],

    ["captain_jun",[10,9,9,"gogy","(icons carry\n pluh"]],
    ["captain_jun",[10,8,9,"saba","lug"]],
    ["captain_jun",[10,7,7,"joshua","Gruggaga"]],
    ["captain_jun",[9,10,8,"viie","noise might be something intentional, but its not something that i perticularly like\n otherwise an interesting blood build from what i can understand"]],
]

var orphantratings = []